/**
 * 카탈로그에 반드시 포함하고 싶은 게임 타이틀 목록.
 * RAWG 의 -added 정렬로는 뒤로 밀리는 국내 온라인/모바일 게임을 이름으로 검색해 편입한다.
 * (RAWG/IGDB 공식 API 에 존재하는 항목만 실제로 들어간다.)
 */
export const SEED_TITLES: string[] = [
  // ── 국내 온라인 (PC) ──
  "League of Legends",
  "Lost Ark",
  "MapleStory",
  "MapleStory 2",
  "Dungeon Fighter Online",
  "Black Desert Online",
  "Lineage",
  "Lineage 2",
  "Lineage 2M",
  "Blade and Soul",
  "Mabinogi",
  "Vindictus",
  "TERA",
  "Sudden Attack",
  "KartRider",
  "KartRider: Drift",
  "Crazy Arcade",
  "Elsword",
  "Closers",
  "Cabal Online",
  "Ragnarok Online",
  "Aion",
  "ArcheAge",
  "The Kingdom of the Winds",
  "Z8Games CrossFire",
  "CrossFire",
  "PUBG: BATTLEGROUNDS",
  "The First Descendant",
  "Dave the Diver",
  "Lies of P",
  "The Finals",
  "Throne and Liberty",

  // ── 국내/아시아 모바일 ──
  "Genshin Impact",
  "Honkai Impact 3rd",
  "Honkai: Star Rail",
  "Zenless Zone Zero",
  "Cookie Run: Kingdom",
  "Cookie Run: OvenBreak",
  "Seven Knights",
  "Summoners War: Sky Arena",
  "Epic Seven",
  "Guardian Tales",
  "Ni no Kuni: Cross Worlds",
  "Odin: Valhalla Rising",
  "Blade and Soul Revolution",
  "Lineage M",
  "Lineage W",
  "MIR4",
  "Dragon Raja",
  "Arknights",
  "Azur Lane",
  "Brown Dust 2",
  "Goddess of Victory: Nikke",
  "Counter-Side",
  "King's Raid",
  "Punishing: Gray Raven",
  "Wuthering Waves",
  "Tower of Fantasy",
  "Marvel Snap",
  "Pokémon UNITE",
  "League of Legends: Wild Rift",
  "Diablo Immortal",
  "Uma Musume: Pretty Derby",
  "Brawl Stars",
  "Clash Royale",
  "Clash of Clans",
  "Raid: Shadow Legends",
  "AFK Arena",

  // ── 콘솔/글로벌 대표작 (탐색 폭 보강) ──
  "Elden Ring",
  "The Legend of Zelda: Tears of the Kingdom",
  "Baldur's Gate 3",
  "Cyberpunk 2077",
  "Hades",
  "Stardew Valley",
  "Final Fantasy XIV",
  "Overwatch 2",
  "Valorant",
  "Counter-Strike 2",
  "Marvel Rivals",
];
